name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GATSBY_SITE_URL: 'https://herasymchuk.com'
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
    # The branch expected by GitHub to have the static files needed for your site.
    # deploy-branch: # optional, default is master
    # Additional arguments that get passed to `gatsby build`.
    # gatsby-args: # optional, default is

